// Generated by gencpp from file turtlesim_expl/GenValue.msg
// DO NOT EDIT!


#ifndef TURTLESIM_EXPL_MESSAGE_GENVALUE_H
#define TURTLESIM_EXPL_MESSAGE_GENVALUE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace turtlesim_expl
{
template <class ContainerAllocator>
struct GenValue_
{
  typedef GenValue_<ContainerAllocator> Type;

  GenValue_()
    : value(0)
    , intrusion()  {
    }
  GenValue_(const ContainerAllocator& _alloc)
    : value(0)
    , intrusion(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _value_type;
  _value_type value;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _intrusion_type;
  _intrusion_type intrusion;




  typedef boost::shared_ptr< ::turtlesim_expl::GenValue_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::turtlesim_expl::GenValue_<ContainerAllocator> const> ConstPtr;

}; // struct GenValue_

typedef ::turtlesim_expl::GenValue_<std::allocator<void> > GenValue;

typedef boost::shared_ptr< ::turtlesim_expl::GenValue > GenValuePtr;
typedef boost::shared_ptr< ::turtlesim_expl::GenValue const> GenValueConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::turtlesim_expl::GenValue_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::turtlesim_expl::GenValue_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace turtlesim_expl

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'turtlesim_expl': ['/home/valentin/thesis/ma-ros_git/catkin_ws/src/turtlesim_expl/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::turtlesim_expl::GenValue_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::turtlesim_expl::GenValue_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::turtlesim_expl::GenValue_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::turtlesim_expl::GenValue_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::turtlesim_expl::GenValue_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::turtlesim_expl::GenValue_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::turtlesim_expl::GenValue_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fff21b1ce4d892d68e646aa7a0d9dac4";
  }

  static const char* value(const ::turtlesim_expl::GenValue_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xfff21b1ce4d892d6ULL;
  static const uint64_t static_value2 = 0x8e646aa7a0d9dac4ULL;
};

template<class ContainerAllocator>
struct DataType< ::turtlesim_expl::GenValue_<ContainerAllocator> >
{
  static const char* value()
  {
    return "turtlesim_expl/GenValue";
  }

  static const char* value(const ::turtlesim_expl::GenValue_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::turtlesim_expl::GenValue_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 value\n\
string intrusion\n\
";
  }

  static const char* value(const ::turtlesim_expl::GenValue_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::turtlesim_expl::GenValue_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.value);
      stream.next(m.intrusion);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GenValue_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::turtlesim_expl::GenValue_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::turtlesim_expl::GenValue_<ContainerAllocator>& v)
  {
    s << indent << "value: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.value);
    s << indent << "intrusion: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.intrusion);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TURTLESIM_EXPL_MESSAGE_GENVALUE_H
