#!/usr/bin/env python
""" Shared data among IDS components """

# APP IDS
GENERATORS = ["GAUSSIAN", "GUMBEL", "LAPLACE", "LOGISTIC", "PARETO", "RAYLEIGH",
	"UNIFORM", "VONMISES", "WALD", "WEIBULL", "ZIPF"]
COLOURS = ["COLOUR"]
POSE_CC = "COUNTRYCODE"
POSE_POI = "POI"
POSE_TSP = "TSPROUTING"
POSES = [POSE_CC, POSE_POI, POSE_TSP]

# POIS
INTRUDED_POI_TYPES = ["private home", "nsa hq"]
INTRUDED_POI_RESULTS = ["Invalid"]

# LABELS
LEGAL_LABELS = ["normal"]
INTRUSION_LABELS_GENS = ["zeroes", "huge-error"]
INTRUSION_LABELS_COLRS = ["red"]
INTRUSION_LABELS_POIS = ["jump", "illegaltype", "routetoself"]
INTRUSION_LABELS = INTRUSION_LABELS_GENS + INTRUSION_LABELS_COLRS + INTRUSION_LABELS_POIS
